### ISSUE TITLE
npm bin doesn't seem to be available on recent versions

### ISSUE THREAD

**Issue by tsyesika** [sobjornstad/tzk#8]
I've noticed that it seems to be 9.x onwards the `npm bin` command which is used in tzk doesn't seem to be available causing for example `tzk init` to fail.

**Comment by sobjornstad** [comment]
Looks like that's mentioned in the changelog as an intentional change:
https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/

Unfortunately `npm exec` isn't available in the older versions, so this is going to be a bit of a pain to fix – will have to detect the version and use an appropriate command. I'll keep it on the list.

Thanks!
Soren

**Comment by gerases** [comment]
maybe just search for the tiddlywiki binary using something like `which` and inform the user as to what should be done if it's not found?

**Comment by sobjornstad** [comment]
Should be fixed in new release 0.4.0.
